apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ngf-console-agent.fullname" . }}-hub
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ngf-console-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  HUB_API_ENDPOINT: {{ .Values.hub.apiEndpoint | quote }}
  HUB_OTEL_ENDPOINT: {{ .Values.hub.otelEndpoint | quote }}
  {{- if .Values.hub.authToken }}
  HUB_AUTH_TOKEN: {{ .Values.hub.authToken | quote }}
  {{- end }}
  {{- if .Values.distributedCloud.enabled }}
  XC_TENANT: {{ .Values.distributedCloud.tenant | quote }}
  XC_API_TOKEN: {{ .Values.distributedCloud.apiToken | quote }}
  XC_NAMESPACE: {{ .Values.distributedCloud.namespace | quote }}
  {{- end }}
