apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ngf-console.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ngf-console.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "ngf-console.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        {{- include "ngf-console.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: {{ include "ngf-console.serviceAccountName" . }}
      containers:
        - name: controller
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          {{- if .Values.xc.enabled }}
          env:
            - name: XC_TENANT_URL
              value: {{ .Values.xc.tenantUrl | quote }}
            - name: XC_DEFAULT_NAMESPACE
              value: {{ .Values.xc.defaultNamespace | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
