apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ngf-console-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ngf-console-controller-role
subjects:
  - kind: ServiceAccount
    name: ngf-console-controller
    namespace: ngf-console-system
